<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    private static $articles = [
        [
            'image' => 'img/restaurant/restaurant_2.jpg',
            'title' => 'A Luxury in the Heart of Nature',
            'quote' => 'In the island of the gods, Bali and in the heart of its cultural center, Ubud, lays Anahata Villas & Spa Resort. 
            Anahata is a boutique resort consisting of 12 villas located right at Petanu river in the hill surrounded by lucious tropical rain forest. It was set up with a vision to be an natural retreat for mind, body and soul.',
            'slug'  => 'luxury-in-the-heart-of-nature',
            'content' => '
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">In the island of the gods, Bali and in the heart of its cultural center, Ubud, lays Anahata Villas &amp; Spa Resort.&nbsp;</span></span></span></p>
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Anahata is a boutique resort consisting of 12 villas located right at Petanu river in the hill surrounded by lucious tropical rain forest. It was set up with a vision to be an natural retreat for mind, body and soul.</span></span></span></p>
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">The resort was built using modern Balinese architecture concept. At the lobby bar and restaurant, your eyes will witness the majestic view of the forest, and your body will feel the cool breeze of the mountain, as your palate enjoys authentic delicious meals.</span></span></span></p>
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">This magnificent panorama can be viewed also from every villa from the living room and the bedrooms.</span></span></span></p>
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">The name of Anahata comes from a sanskrit word, which means love, compassion and harmony. In yoga it signifies as the heart charka the center of energy located in the heart region.</span></span></span></p>
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Anahata is perfect not only for honeymooners, but also for family holiday and group/corporate gathering. Anahata is a </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>family sanctuary</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">. There are plenty of activities for everyone for adults and children. &quot; To win customers, we must offer something unique such as private barbeque in the garden, horse riding, DVD player in every villa and Xbox video game for the children,&quot; said Mrs. Onnie Djatmiko, the owner of the beautiful resort.</span></span></span></p>
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Spa and Yoga also play major themes in this resort. The spa menu is Simply impressive: full body massage, facial treatment, herbal backrub, flower bath and so on. This spa treatment will make you feel brand new. You can have it in the spa house or you own villa. The honeymooners and couple must try its asmaradana treatment a 100 minute massage and herbal bath done by professional therapist in a very romantic setting. At a spa house located just next to the river and bird singing.</span></span></span></p>
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">On the weekends, yoga courses are offered free of charge to the guest. Even beginners will feel the benefits of the exercise, which make them fell really relaxed and energized.</span></span></span></p>
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Going down to the river bank is definitely a must. You will find splendor of natural beauty along the way.</span></span></span></p>
            '
        ],
        [
            'image' => 'img/restaurant/restaurant_1.jpg',
            'title' => 'A Trully Holiday Escape For Familly',
            'quote' => "Stay in Ubud a few days and you quickly find it's the place to do leisurely activities nearby our resort. You can venture out to explore the place of interests such as Monkey Forest, Pura Tirta Empul which is a holy bathing place since the 10th century, Antonio Blanco Museum, Bali Safari & Marine Park, Balinese Dance Performance at Puri Ubud. Otherwise, along the way to Ubud Market, the streets are lined with galleries, art shops and boutiques. There's much more some of the famous landmarks which you can travel around. Special service from Anahata Villas & Spa Resort, we offer free shuttle Ubud Market based on schedule every day. Thus, it will complete your truly holiday.",
            'slug'  => 'a-trully-holiday-escape-for-family',
            'content' => "Stay in Ubud a few days and you quickly find it's the place to do leisurely activities nearby our resort. You can venture out to explore the place of interests such as Monkey Forest, Pura Tirta Empul which is a holy bathing place since the 10th century, Antonio Blanco Museum, Bali Safari & Marine Park, Balinese Dance Performance at Puri Ubud. Otherwise, along the way to Ubud Market, the streets are lined with galleries, art shops and boutiques. There's much more some of the famous landmarks which you can travel around. Special service from Anahata Villas & Spa Resort, we offer free shuttle Ubud Market based on schedule every day. Thus, it will complete your truly holiday."
        ],
        [
            'image' => 'img/restaurant/restaurant-night.jpg',
            'title' => 'Anahata Villa & Spa Resort',
            'quote' => 'Anahata Villa & Spa Resort bisa jadi sanctuary Anda',
            'slug'  => 'anahata-villa-spa-resort',
            'content' => '
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Bicara Bali tentu tak hanya membahas keindahan pantainya saja. Namun, daya tarik daratan pulau Dewata ini pun tak kalah eksotisnya. Kawasan Ubud merupakan tempat yang harus disambangi dan Anahata Villa &amp; Spa Resort bisa jadi sanctuary Anda dan si dia. Gemericik air sungai Petanu dan hamparan hijau pepohonan tak hanya menambah keindahan alam namun juga memberi suasana nan damai.&nbsp;</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Tempat ini hanya memiliki 12 villa di atas perbukitan. Maka, suasana sekitar amatlah tenang. Dijamin acara bermesraan bakal berjalan lancer, tak ada yang mengusik, tak ada yang mengintip. Setiap villa di Anahata merupakan bangunan tiga tingkat yang masing-masing dilengkapi dengan kolam renang dan taman yang cantik. Resort ini juga dilengkapi dengan restoran, fitness center, yoga room dan internet access. Bagi mereka yang doyan beryoga maka Anahata adalah tempat yang cocok. Sebuah paket honeymoon yang lengkap dengan program yoga bisa disiapkan untuk anda berdua. Tak ketinggalan tentu saja berbagai paket spa treatment yang juga siap buat memanjakan tubuh agar jadi lebih segar.&nbsp;</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Segera putar nomor telepon 0361 9789912 atau coba lihat www.anahataresort.com</span></span></span></p>
            '
        ],
        [
            'image' => 'img/restaurant/restaurant-night.jpg',
            'title' => 'Anahata Villas & Spa Resor',
            'quote' => 'Bersenang-senang dan bersantai di Bali, merupakan tujuan utama bagi wisatawan yang berkunjung ke Bali. Banyak pilihan kegiatan bersantai dan menghibur di luar ruangan yang menjadi pilihan. Pilihan kegiatan ini bergantung pada usia, karena beberapa dari kegiatan tersebut memerlukan kesiapan fisik, seperti bersepeda dan berkuda.
            Lingkungan alam Ubud Bali, menyajikan keindahan dan keunikan yang menarik untuk dinikmati ditambah lagi dengan udaranya yang bersih dan sejuk. Bagi kaum turis dan keluarganya yang biasanya datang dari kota besar suasana seperti yang disuguhkan alam Ubud ini sangat didambakan.',
            'slug'  => 'anahata-villa-spa-resort-2',
            'content' => '
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>Bersepeda, Berkuda dan Yoga</strong></span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>Bersenang-senang dan bersantai di Bali</strong></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">, merupakan tujuan utama bagi wisatawan yang berkunjung ke Bali. Banyak pilihan kegiatan bersantai dan menghibur di luar ruangan yang menjadi pilihan. Pilihan kegiatan ini bergantung pada usia, karena beberapa dari kegiatan tersebut memerlukan kesiapan fisik, seperti bersepeda dan berkuda.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>Lingkungan alam Ubud Bali,</strong></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> menyajikan keindahan dan keunikan yang menarik untuk dinikmati ditambah lagi dengan udaranya yang bersih dan sejuk. Bagi kaum turis dan keluarganya yang biasanya datang dari kota besar suasana seperti yang disuguhkan alam Ubud ini sangat didambakan.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>Kegiatan bersepeda,</strong></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> sangat cocok dilakukan di kawasan ini. Dengan bersepeda, semua pemandangan alam dan kenyamanan itu dapat dinikmati, karena dengan kendaraan roda dua ini dapat dijangkau daerah-daerahn di sekitar tempat menginap. Melalui jalan-jalan kecil pedesaan bersepeda terasa nyaman dan aman karena jalan ini tidak dilalui kendaraan roda empat. Bagi mereka yang cukup kuat mengayuh sepeda kenikmatan lebih terasa meskipun ada jalan yang mendaki atau tidak terlalu mulus.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>Melihat kegiatan pendudukan desa,</strong></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> sawah, kebun, alam pegunungan dan sungai yang airnya jernih merupakan hal yang menyenangkan ketika kita melancong ke Ubud. Selain bersepeda para wisatawan dapat pula menikmati lingkungan dengan menunggang kuda yang dapat disewa. Dengan berkuda kelelahan seperti mengayuh sepeda mungkin tidak terasa tetapi diperlukan posisi duduk yang tepat sehingga tidak menyebabkan pegal di pinggang karena guncangan langkah kuda.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>Dipandu seorang pengendali kuda, </strong></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">kegiatan berkuda cukup asyik untuk dilakukan, terutama untuk lingkungan yang jalannya mendaki. Namun, dengan berkuda tidak terlalu jauh menjangkau pelosok-pelosok desa. Pilihan berkuda memang tepat bagi remaja dan anak-anak, karena selain mereka mengenal lingkungan, mereka juga belajar menjaga keseimbangan tubuh.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>Selain bersepeda dan menunggang kuda</strong></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">, adapula kegiatan lain yang tidak banyak menguras tenaga tetapi efeknya dapat menyegarkan pikiran dan tubuh. Kegiatan tersebut adalah melakukan yoga yang dipandu oleh instruktur yoga. Fasilitas beryoga yang ada berupa ruang tertutup yang hening atau di ruang terbuka yang khusus untuk yoga. Di Anahata Ubud, fasilitias tersebut telah disiapkan dengan baik. Bahkan beberapa instruktur yoga juga siap memandu kegiatan tersebut bagi para pemula. Yang menarik disini adalah lokasi yoga yang berada diluar ruang, yaitu di bantaran sungai. Area yoga berupa dek kayu yang menjorok ke aliran sungai.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>Suasana alami</strong></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">, suara gemuruh air sungai serta udara yang sejuk merupakan paduan yang ideal untuk melakukan kegiatan yoga. Bersepeda, berkuda dan melakukan yoga sungguh merupakan kegiatan yang sangat menyenangkan. Di Bali, anda dapat mereguk kesenangan ini.</span></span></span></p>

            <p>&nbsp;</p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>Nikmatnya beraktifitas di alam terbuka.</strong></span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Mengisi kegiatan liburan di Balu sangat beragam yang dapat dilakukan mulai dari matahari terbit sampai dini hari para wisatawan dapat melakukan kegiatan ini di alam terbuka yang indah baik di darat, laut/sungai maupun di udara.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Di Bali pelayanan terhadap aktivitas luar ini banyak tersedia seperti hotel, resort, dan vila. Bahkan beberapa paket untuk ikut kegiatan ini dapat dipesan dari agen-agen tur pariwisata yang terebar baik di setiap kota besar indonesia maupun mancanegara.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Banyak wisatawan domestik telah merancang kegiatan ini sejak awal pemesanan paket tur mereka. Hal ini akan lebih memudahkan mereka nanti ketika sampai tujuan tanpa perlu repot mengatur jadwal transportasi. Di tinjau dari sudut biaya hal ini pun lebih menguntungkan.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Kegiatan luar ruang di darat antara lain, berjalan kaki, bersepeda dan menunggang kuda di sekitar lingkungan. Di Ubud fasilitas ini tersedia bahkan ada juga atraksi unik seperti trip menunggang gajah dan onta dan </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>land touring</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> dengan mengendarai </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>land rover</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Kegiatan ini pada dasarnya menjelajahi alam di kawasan Bali yang masih alami sambil melihat denyut kehidupan masyarakat desa di Bali yang jarang dilewati kendaraan umum. Dalam beberapa paket yang ditemui Griya asri di Ubud dan candi dasa, kegiatan berjalan kaki, juga diisi dengan kunjungan kepada perajin tradisional yang membuat kerajinan anyaman, patung, lukisan, batu bata atau membuat garam. Di samping itu pengalaman yang juga mengasyikan adalah penjelajahan alam seperti memasuki hutan lindung Bali barat, mendaki gunung atau menyebrang danau di sekitar Gunung Agung dan danau Batur.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Kegiatan bersantai di laut yaitu sepanjang pantai di Bali telah dikenal di seluruh dunia. Pantai Kuta misalnya adalah magnet utama yang banyak menyedot turis eropa untuk datang ke Bali. Kegiatan yang umum dilakukan di laut adalah berenang, berjemur di pantai atau mencoba bungy jumping di AJ Hackett pantai Legian.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Kawasan pantai di Bali menyajikan kegiatan yang berbeda disesuaikan dengan keadaan lautnya. Untuk laut yang berombak besar dengan pesisir pantai landai berpasir, seperti Kuta dan Uluwatu, kegiatan </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>surving</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> adalah yang utama dilakukan turis. Pantai lain yang agak berkarang seperti </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>Hotdog</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> Tanjung Benoa menyajikan kegiatan seperti </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>jet ski, banana boat, flying fish </em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">dan</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em> wind surving. </em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Yang juga menarik adalah kegiatan</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em> parasailing </em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">yaitu menaiki parasut yang ditarik </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>boat</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> dengan tali di Leo&#39;s Water Sport Tanjung Benoa kegiatan ini dapat dilakukan oleh semua usia yang berani berbasah-basah.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Resor di kawasan benoa juga menyediakan perlengkapan untuk wind surving atau para surving. Kawasan laut diseputar Bali mempunyai alam yang berbeda. Di kawasan Pulau Menjangan Bali barat, Amed dan Amlapura Bali Timur, Candi Dasa Bali Tenggara dikenal dengan ikan-ikan dan terumbu karangnya yang indah, sehingga kegiatan </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>snorkling</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> ideal dilakukan disini. Kegiatan menyelam merupakan daya tarik dan agenda utama disini. Di sekitar pantai Lovina Singaraja, terdapat atraksi menarik yaitu melihat lumba-lumba saat fajar menyingsing.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Kegiatan rekreasi di udara Bali, memang belum banyak di kenal. Namun beberapa penyelenggara kegiatan ini telah tersedia seperti gantole, penyewaan helikopter dan pesawat ringan yang terbang kebeberapa kawasan di Bali, Lombok dan Sumbawa. Bagi anda yang tidak berani berada di ketinggian, mungkin cukup menyenangkan bermain layang-layang di pantai.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>Rekreasi di sungai dan laut</strong></span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Sungai dan laut di pulau bali merupakan area berwisata yang sangat diminati turis. Di sungai dan laut di pulau dewata ini kita dapat melakukan berbagai kegiatan&nbsp; seperti rafting, arung jeram, selancar, menyelam dan memancing ikan.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Salah satu kegiatan yang sangat diminati para turis ialah berarung jeram di sungai yang berarus deras. Para peserta yang biasanya terdiri atas 4 sampai 6 orang termasuk pemandu menaiki perahu karet yang kadang-kadang membentur batu sungai baik depan, disamping maupun di belakang. Sepanjang mengarungi sungai dan menikmati keindahan alam ini peserta dapat menghirup udara segar yang tidak pernah ditemui di kota-kota. Bertualang di sungai lewat olahraga arung jeram ini mendebarkan ini memang sangat mengasyikan. Di bali banyak sekali terdapat tempat-tempat untuk berolahraga araung jeram ini. Salah satu diantaranya yang cukup popular adalah puri rafting yang memanfaatkan sungai ayung ubud. Menurut banyak orang yang telah sering mengikuti olahraga arung jeram, sungai-sungai di bali merupakan tempat yang mengasyikan dan menarik. Mulai dari daerah bongkasa (45 km dari Denpasar) berakhir di Puri Banyuning Mengwi.&nbsp;</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Salah satu manfaat olahraga ini adalah dapat memotivasi semangat kerjasama. Diantara para peserta dituntut menjalin kerjasama dalam menghadapi berbagai kemungkinan datangnya bahaya yang menghadang</span></span></span></p>
            '
        ],
        [
            'image' => 'img/restaurant/restaurant-night.jpg',
            'title' => 'Anahata Villas & Spa Resort: Discovering the Lost Paradise in Ubud Bali',
            'quote' => '',
            'content' => '
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Staying in villas is becoming a trend in Bali, as it offers much different holiday experience compared with staying in normal hotels. Generally, people get more privacy and more personalized service if they stay in villas, which are mostly run like a boutique hotel.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Another new trend is the growing popularity of Ubud, as tourist destination in Bali.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Why Ubud? The answer is because Ubud is unique. The first timers to Bali will definitely choose to stay in Kuta, Nusa Dua or Seminyak. But in our opinion there are many places all over the world that offer beautifull beaches like Hawaii, Florida, Gold Coast, Maldives, Mauritius, etc. But a place like Ubud with its rich, unique can not be found anywhere else in the world.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Ubud has been known as the heart of bali&#39;s cultural center. it has always been an enhancing place for many artist, even foreign artist like Blanco, Le Meyeur, Aric Smith and many others, choose to live in Ubud until the end of their lives. It has always been a source of inspiration for artist and art lovers. Ubud especially appeals to wealther and more sophisticated tourist, as these people are more attracted to arts and cultures. It is famous for its art galleries.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Another factor that makes Ubud a great place to visit is its cool weather and beautifull scenery. Ubud is also famous for its beautiful sceneries of the mountain, paddy field terraces, tropical rain forest, and the rivers are breathtaking.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">During our honeymooner trip to Ubud, Bali we discover Anahata Villas &amp; Spa Resort, a paradise lost. This luxurious boutique resort is located right in the heart of nature far away from noise and disturbances. It lies on a hill surrounded by tropical rain forest besides Petanu Rivers. this resort is blessed with a natural beauty, wonderful landscape and scenery, the sounds of the swirling water and birds singing within the resort as well as the cool breeze of the mountain. Interestingly, sometimes you see monkeys, the native inhabitants of this forest, visiting Anahata properties.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Onnie, the owner of this beautiful resort exaplains to us her vision about Anahata. She said &quot; I name this resort Anahata, which in sanskrit means love and harmony. We want this resort to be &#39;A Natural Retreat for Mind, Body and Soul,&#39; whereby, we want to treat our guest wholly so that they completely fresh when they go home.&quot;</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Our first impression: this is a perfect hide away for honeymoon. The resort was built using modern balinese architecture. Though it looks very stylish and contemporary, the balinese elements appear very strongly here through the use of traditional balinese ornaments, artworks, woods and natural stones.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">It is obviously that the architech wants to make the most of the majestic environment. From the open air lobby bar and restaurant, we can gaze outward across marvelous landscape of the tropical rain forest.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">The view from our villa is breathtaking although it&#39;s obvious that actually every villa has a beautiful view of landscaped garden merged with mother nature.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">After resting for a while, we can&#39;t wait to walk around the resort and to know what we can do in this resort. First, we go to the main pool and then dip in the hot whirlpool. It&#39;s just so relaxing. And then we go down to the river bank. We feel totally immersed with the serenity and beauty of the nature, bringing back the harmony in our mind, body and soul. We sit around for hours on the river side. the water is so clear and cool; it&#39;s so irresistible that we decide to jump into the water and swim in the river. It&#39;s just so refreshing.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">From the river bank we walk up to the spa pavilion located by the river side to try the spa treatment. It&#39;s a different experience, indeed. As your body is enjoying the massages, you feel like your mind drifting away flowing with the sound of the river. It&#39;s rejuvenating.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">For our dinner, we try Anahata&#39;s famous Balinese Rijstafel served in candlelight dinner. The crispy duck is delicious to the bone; the sambal is just tasty; the desert is really yummy. Unfortunately, we have no more space in our stomach to try all the dishes in Anahata menu. &quot;Anahata is totally aware that delicious and healthy food is a must for a successful holiday. We include not only authentic balinese food but also western and asian cuisine as well as vegetarian dishes,&quot; said Onnie.&nbsp; We end the night feeling great with that we have done the whole day. It&#39;s time to enjoy our beautiful room and cozy bed.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">The next morning before breakfast, we took a time to walk around the neighborhood village. breathing the fresh morning air while enjoying the view of the rice fields with a mountain of Gunung Agung in the backdrop give a peaceful and happy feeling.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">We figure that as a honeymooner we must try the kamasutra yoga class to make our experiences in Anahata complete. The class was lead by an experienced yoga instructor.&nbsp; Being a yoga lover herself, Onnie said: &quot; yoga is a central theme in Anahata.&quot; I guess this is a part of her program to treat her guests mind, body &amp; soul. Because even as beginners, we do feel the benefits of this wonderful exercise which make our whole being relaxed and energized.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">After staying two nights in Anahata, it&#39;s time for us to go home. We must go back to a real world. Our experiences in Anahata may be one of the most romantic and unforgetable holidays we have ever had. We can&#39;t wait to go back there.</span></span></span></p>
            ',
            'slug' => 'discovering-the-lost-paradise'
        ],
        [
            'image' => 'img/spa/spa_room_1.jpg',
            'title' => "Bali High",
            'quote' =>  "Despite being well-trodden by tourist, Bali can still surprise the holiday-maker who takes the road less travelled. There are places deep in the pastoral heart of Bali, away from the camera-toting crowds of Kuta, Legian and ubud, that provide a spiritual respite and a deep communion with nature. Such places have an energy that artists and writers seek, to find inspiration for their work.",
            'slug' => "bali-high",
            'content' => '
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Despite being well-trodden by tourist, Bali can still surprise the holiday-maker who takes the road less travelled. There are places deep in the pastoral heart of Bali, away from the camera-toting crowds of Kuta, Legian and ubud, that provide a spiritual respite and a deep communion with nature. Such places have an energy that artists and writers seek, to find inspiration for their work.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">And it is this quality that has drawn many investors to build a &ldquo;temple&rdquo; at the site to tap into energies both environtmental and elemental, to provide a well appointed resting place where the city and work weary can recharge and rejuvenate call it sanctuary if you like.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Accessed via a series of narrow, winding roads often flanked on both sides by house or rice fields stretching as far as the eye can see&nbsp; the Anahata Villa and Spa Resort just north of Ubud is known to few locals and even fewer travelers. The 12 villas at the top of a gentle climb are furnished in five star comfort.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Built as a family retreat, each villa has three levels: at ground level, enter the living and dining rooms attached to a kitchen; downstairs are two bed rooms with ensuite bathrooms and a small living area with a patio, which opens out onto the private plunge pool and garden; the very spacious master bedroom is on the top level, complete with a kinky shower which features a glass wall- so you can watch while your partner takes a shower!</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">The modern Balinese villas all face the main pool and gardens, and the drop of the lanc beyond, so the view from the balcony is superb. Follow the pebble-paved stairway and it will take you down to the Petanu river. At the bottom is a natural pool the colour of jade, translucent and shimmering. There are many perfect places on earth, and this is one of them. It is always cool here in the protective green shade of te surrounding flora. Imagine meditating on the wooden deck folating on the water&hellip;in such serene spots we are a step closer to transcending the self and getting in touch with the soul, becoming one with nature.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Kundalini yoga lessons, focusing on breathing techniquers, are free during the weekends (Fridays-Sundays); on other days, there is a small fee for the one and a half hour class. The yoga exercise are calming and energizing, helping to increase focus and clear the mind.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Anahata has a full spa and massage menu, including a herbal backrub, rice scrub, slimming treatment, shiatsu, acupressure massage and one for honeymooners and couples using a specially blended oil said to have the aroma of love! The massage can be arranged in the privacy of your villa or outdoors in one of the gazebos. A vegetarian diet can also be arranged.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">The possibilities while enjoying a stay here are numerous. The rice fields surrounding the resort are particularly tempting. It is extremely soothing just to sit in the middle off all that greenery. An entire morning can be whiled away with the friendly farmers to learn from them why&nbsp; there is no need to make haste; they never seem to be in any hurry.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Children have fun in the fields pretending to be scarecrows to shoo away the birds from pecking at the rice or running after the </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>bebek </em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">&ndash; most of the </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>bebek</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> end up as crispy skinned duck, a Balinese specially. Join the Balinese children at kite flying, something that will surely make the spirit soar as well.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Another idea world be to spend the morning with a good book in one of the pavilions in the sprawling garden, reposing among the white cushions. White clad pavilions somehow speak of romance and the luxe life.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">It is a great place to cure you of retail therapy nonsense you have fallen into in the city &ndash; in such great surroundings, walking barefoot gets you &ldquo;earthed&rdquo; again and shopping will be the furthest thing from your mind &ndash; anyway, you really don&rsquo;t need yet another </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>sarong</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> or tacky beaded bag or wooden duck.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>Other activities</strong></span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Explore the villages, go on a guided trek, or go biking and horse riding. Conceived as a family retreat, the resort is completely child friendly. For the enthusiastic cook, Ubud is only 15 minutes away, and you can visit the market or sign up for the Balinese cooking classes offered by several reaturants in town</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>Bookings</strong></span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Various packages are available, from Family, Spa or Yoga to those just for honeymooners and couple. A 2N/3D couples package for example, is about RM1500, inclusive of a spa treatment, Balinese dinner, daily breakfast, etc. Check the website for the latest prices.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>Getting there</strong></span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">The resort is located in Tampak Siring, a 10 minute drive from Ubud, and over an hour&rsquo;s drive from the Ngurah Rai International Airport. The room package is inclusive of airport transfers, which saves you a lot of trouble figuring out how to get there. For self drive holidays, a good map is essential; always stop and check your directions with the locals (a rough guide is available on the website). Bear in mind that you may sometimes need to ask half a dozen people before you get pointed in the right direction, or before you find someone who knows that you are talking about &ndash; and that&rsquo;s generally how it is when you navigate Bali by road. The Balinese are always helpful and are full of good intensions, but they don&rsquo;t always have good knowledge of their own villages. Live grooves to a different beat here.</span></span></span></p>
            '  
        ],
        [
            'image' => 'img/spa/spa_room_1.jpg',
            'title' => "Hening di Anahata Spa",
            'quote' => "Alam yang hening, wangi rempah, serta suara air, menyatu menciptakan sebuah 'sensasi' indah di spa treatment.
            Semburat cahaya matahari dari balik tebing-tebing bebatuan curam, yang ditumbuhi lumut-lumut, pepohonan berdaun lebat saling bergelayut, serta petak-petak sawah yang berundak-undak, menjadi identik dengan sebuah desa bernama Ubud. Lekukan anak sungai yang seakan bersembunyi di antara tebing, mengalir tenang, bening mericik tersandung batu-batu kali Sungai Petanu. Sungai 'milik' masyarakat Ubud.",
            'slug'  => "hening-di-anahata-spa",
            'content'   => '
            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Alam yang hening, wangi rempah, serta suara air, menyatu menciptakan sebuah &quot;sensasi&quot; indah di spa treatment.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Semburat cahaya matahari dari balik tebing-tebing bebatuan curam, yang ditumbuhi lumut-lumut, pepohonan berdaun lebat saling bergelayut, serta petak-petak sawah yang berundak-undak, menjadi identik dengan sebuah desa bernama Ubud. Lekukan anak sungai yang seakan bersembunyi di antara tebing, mengalir tenang, bening mericik tersandung batu-batu kali Sungai Petanu. Sungai &quot;milik&quot; masyarakat Ubud.</span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Alam Ubud yang hening, memberikan kesejukan jiwa, menjadi tempat sebuah vila bermuatan nilai filosofi </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>love, compassion, and harmony</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">, Anahata Villas &amp; Spa Resort yang mengangkat </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>a natural retreat for mind</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">. </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>Close to nature</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> yang terkemas dalam </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>healthy lifestyle</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">. Sebuah lingkungan tenang, seakan dikelilingi oleh rimbunnya hutan tropis yang kental dengan privasi tinggi berfasilitas, seperti area </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>deck</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> berlantai kayu, kolam renang, area meditasi, ataupun perawatan tubuh, seperti </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>spa treatment</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> yang menawarkan</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em> full body massage, facial treatment, herbal backrub,</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> serta </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>flower bath.</em></span></span></span></p>

            <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Lokasi spa ini berada pada posisi &quot;undakan&quot; bawah. Untuk menuju ke area spa tersebut sebuah jalan setapak yang dirancang dengan ulikan motif memberikan kesegaran alam imajinasi kita. Area spa ini memiliki dua area, </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>indoor -spa pavilion</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> yang dirancang bergaya gazebo- serta </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em>outdoor spa</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> dengan open air bale. Seluruhnya tertata dalam layout yang seakan berundak-undak mengikuti keberadaan kontur tanah pegunungan. Hening, hijau, suara gemericik air pada batu-batu kali, desir angin yang menggoda, suara gesekan daun hulan tropis, serta wangi magis rempah-rempah yang tersedia menciptakan sensasi</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><em> spa treatment</em></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> Anahata Villas &amp; Spa Resort yang sempurna.</span></span></span></p>
            '
        ]
    ];

    public static function getAll()
    {
        return self::$articles;
    }

    public static function find($slug)
    {
        $articles = self::$articles;
        $result = [];

        foreach($articles as $article) {
            if ($article['slug'] == $slug) {
                $result = $article;
            }
        }

        return $result;
    }
}
